package com.nw.edu.ui;

import com.nw.edu.constants.Constants;
import com.nw.edu.util.FBUtil;
import com.nw.edu.util.TextFieldLimit;
import com.nw.edu.util.Validations;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;

/**
 *
 * @author Home
 */
public class FoodBlogger extends javax.swing.JFrame {

    private String imgFileName = null;
    private int chefId = 0;
    private int recipeId = 0;

    /**
     * Creates new form FoodBlogger
     */
    public FoodBlogger() {
        initComponents();
        FBUtil.loadCategories(categoryCombo);
        new FBUtil().populateTable(chefRecipeTbl);
        userNameTxt.setDocument(new TextFieldLimit(20));
        firstNameTxt.setDocument(new TextFieldLimit(20));
        lastNameTxt.setDocument(new TextFieldLimit(20));
        phoneTxt.setDocument(new TextFieldLimit(10));
        servingsTxt.setDocument(new TextFieldLimit(3));
        ingredientsTxt.setDocument(new TextFieldLimit(3));

        //disable update and delete during page load
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chefRecipeTbl = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        chefUserPanel = new javax.swing.JPanel();
        chefUserPanel1 = new javax.swing.JPanel();
        userNameLbl = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        firstNameLbl = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        recipePanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        servingsLbl = new javax.swing.JLabel();
        servingsTxt = new javax.swing.JTextField();
        glutenLbl = new javax.swing.JLabel();
        glutenCombo = new javax.swing.JComboBox<>();
        difficultyLbl = new javax.swing.JLabel();
        difficultyCombo = new javax.swing.JComboBox<>();
        ingredientsLbl = new javax.swing.JLabel();
        ingredientsTxt = new javax.swing.JTextField();
        descLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTxtArea = new javax.swing.JTextArea();
        categoryLbl = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();
        recipeLbl = new javax.swing.JLabel();
        recipePhotoDisplayLbl = new javax.swing.JLabel();
        browseBtn = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Food Blogger Application");
        setName("Main Frame"); // NOI18N

        mainPanel.setBackground(new java.awt.Color(51, 0, 153));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chefRecipeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "chefId", "username", "firstname", "lastname", "email", "phoneno", "recipeid", "title", "servings", "gluten free", "level", "tot ingredients", "category", "description", "recipe image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chefRecipeTbl.setShowGrid(true);
        jScrollPane1.setViewportView(chefRecipeTbl);

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(viewBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewBtn))
        );

        chefUserPanel.setBackground(new java.awt.Color(0, 153, 255));

        chefUserPanel1.setBackground(new java.awt.Color(0, 153, 255));
        chefUserPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chefUserPanel1.setAlignmentY(30.0F);

        userNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        userNameLbl.setText("Username");

        userNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameTxtKeyPressed(evt);
            }
        });

        firstNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        firstNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        firstNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLbl.setText("FirstName");

        firstNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameTxtKeyPressed(evt);
            }
        });

        lastNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameTxtKeyPressed(evt);
            }
        });

        lastNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lastNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLbl.setText("LastName");

        emailLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 255, 255));
        emailLbl.setText("Email");

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTxtKeyPressed(evt);
            }
        });

        phoneLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phoneLbl.setForeground(new java.awt.Color(255, 255, 255));
        phoneLbl.setText("PhoneNo");

        phoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtActionPerformed(evt);
            }
        });
        phoneTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneTxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout chefUserPanel1Layout = new javax.swing.GroupLayout(chefUserPanel1);
        chefUserPanel1.setLayout(chefUserPanel1Layout);
        chefUserPanel1Layout.setHorizontalGroup(
            chefUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chefUserPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(firstNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lastNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(emailLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(phoneLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        chefUserPanel1Layout.setVerticalGroup(
            chefUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chefUserPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(chefUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLbl)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLbl)
                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLbl)
                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chefUserPanelLayout = new javax.swing.GroupLayout(chefUserPanel);
        chefUserPanel.setLayout(chefUserPanelLayout);
        chefUserPanelLayout.setHorizontalGroup(
            chefUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(chefUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chefUserPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(chefUserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        chefUserPanelLayout.setVerticalGroup(
            chefUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
            .addGroup(chefUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chefUserPanelLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(chefUserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        recipePanel.setBackground(new java.awt.Color(0, 102, 153));

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Title");

        titleTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleTxtKeyPressed(evt);
            }
        });

        servingsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        servingsLbl.setForeground(new java.awt.Color(255, 255, 255));
        servingsLbl.setText("No Of Servings");

        servingsTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                servingsTxtKeyPressed(evt);
            }
        });

        glutenLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        glutenLbl.setForeground(new java.awt.Color(255, 255, 255));
        glutenLbl.setText("Is Gluten Free");

        glutenCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        difficultyLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        difficultyLbl.setForeground(new java.awt.Color(255, 255, 255));
        difficultyLbl.setText("Difficulty Level");

        difficultyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5" }));

        ingredientsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ingredientsLbl.setForeground(new java.awt.Color(255, 255, 255));
        ingredientsLbl.setText("No Of Ingredients");

        descLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descLbl.setForeground(new java.awt.Color(255, 255, 255));
        descLbl.setText("Description");

        descTxtArea.setColumns(20);
        descTxtArea.setLineWrap(true);
        descTxtArea.setRows(5);
        descTxtArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(descTxtArea);

        categoryLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categoryLbl.setForeground(new java.awt.Color(255, 255, 255));
        categoryLbl.setText("Category");

        recipeLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recipeLbl.setForeground(new java.awt.Color(255, 255, 255));
        recipeLbl.setText("Recipe Picture");

        recipePhotoDisplayLbl.setBackground(new java.awt.Color(255, 255, 255));
        recipePhotoDisplayLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recipePhotoDisplayLbl.setOpaque(true);

        browseBtn.setBackground(new java.awt.Color(102, 102, 102));
        browseBtn.setForeground(new java.awt.Color(255, 255, 255));
        browseBtn.setText("Choose File");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        imgLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        imgLabel.setText(" ");
        imgLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgLabel.setOpaque(true);

        javax.swing.GroupLayout recipePanelLayout = new javax.swing.GroupLayout(recipePanel);
        recipePanel.setLayout(recipePanelLayout);
        recipePanelLayout.setHorizontalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recipePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(servingsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servingsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(glutenLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(glutenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(difficultyLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(difficultyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(ingredientsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingredientsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addComponent(categoryLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(descLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(recipeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recipePanelLayout.createSequentialGroup()
                                .addComponent(recipePhotoDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseBtn))
                            .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        recipePanelLayout.setVerticalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl)
                    .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultyLbl)
                    .addComponent(difficultyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientsLbl)
                    .addComponent(ingredientsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glutenLbl)
                    .addComponent(glutenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servingsLbl)
                    .addComponent(servingsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryLbl)
                            .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recipePanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(descLbl))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recipePhotoDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(recipePanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(recipeLbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recipePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(browseBtn)
                                .addGap(55, 55, 55)))
                        .addComponent(imgLabel)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chefUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(recipePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addComponent(chefUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recipePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(saveBtn);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(updateBtn);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(deleteBtn);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(resetBtn);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTxtKeyPressed
        Validations.allowOnlyLettersandSpace(evt, userNameTxt);
    }//GEN-LAST:event_userNameTxtKeyPressed

    private void firstNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTxtKeyPressed
        Validations.allowOnlyLettersandSpace(evt, firstNameTxt);
    }//GEN-LAST:event_firstNameTxtKeyPressed

    private void lastNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTxtKeyPressed
        Validations.allowOnlyLettersandSpace(evt, lastNameTxt);
    }//GEN-LAST:event_lastNameTxtKeyPressed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void emailTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtKeyPressed

    private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtActionPerformed

    private void phoneTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTxtKeyPressed
        Validations.allowOnlyNumbers(evt, phoneTxt);
    }//GEN-LAST:event_phoneTxtKeyPressed

    private void titleTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleTxtKeyPressed
        Validations.allowOnlyLettersandSpace(evt, titleTxt);
    }//GEN-LAST:event_titleTxtKeyPressed

    private void servingsTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_servingsTxtKeyPressed
        Validations.allowOnlyNumbers(evt, servingsTxt);
    }//GEN-LAST:event_servingsTxtKeyPressed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        JFileChooser chooseFile = new JFileChooser();

        //Filtering the image files for specific extensions during upload
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        chooseFile.addChoosableFileFilter(fileFilter);

        int showDialog = chooseFile.showOpenDialog(null);
        if (showDialog == JFileChooser.APPROVE_OPTION) {
            File imageFile = chooseFile.getSelectedFile();
            imgFileName = imageFile.getAbsolutePath();
            imgLabel.setText(imgFileName);

        }
        displayImage();
    }//GEN-LAST:event_browseBtnActionPerformed

    private void displayImage() {
        ImageIcon imgIcon = new ImageIcon(imgFileName);
        Image img = imgIcon.getImage().getScaledInstance(recipePhotoDisplayLbl.getWidth(), recipePhotoDisplayLbl.getHeight(), Image.SCALE_SMOOTH);
        recipePhotoDisplayLbl.setIcon(new ImageIcon(img));
    }

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        if (chefRecipeTbl.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select the table row to view.");
        } else {
            int row = chefRecipeTbl.getSelectedRow();
            TableModel model = chefRecipeTbl.getModel();
            System.out.println(model.getValueAt(row, 0));
            chefId = Integer.parseInt(model.getValueAt(row, 0).toString());
            userNameTxt.setText(model.getValueAt(row, 1).toString());
            firstNameTxt.setText(model.getValueAt(row, 2).toString());
            lastNameTxt.setText(model.getValueAt(row, 3).toString());
            emailTxt.setText(model.getValueAt(row, 4).toString());
            phoneTxt.setText(model.getValueAt(row, 5).toString());
            recipeId = Integer.parseInt(model.getValueAt(row, 6).toString());
            titleTxt.setText(model.getValueAt(row, 7).toString());
            servingsTxt.setText(model.getValueAt(row, 8).toString());
            glutenCombo.setSelectedItem(model.getValueAt(row, 9).toString());
            difficultyCombo.setSelectedItem(model.getValueAt(row, 10).toString());
            ingredientsTxt.setText(model.getValueAt(row, 11).toString());
            categoryCombo.setSelectedItem(model.getValueAt(row, 12).toString());
            descTxtArea.setText(model.getValueAt(row, 13).toString());
            imgLabel.setText(model.getValueAt(row, 14).toString());
            imgFileName = imgLabel.getText();
            displayImage();
            String[] options = {"Update", "Delete", "Cancel"};
            var userAction = JOptionPane.showOptionDialog(null,
                    "Do you want to Update or Delete the selected row?",
                    "Select one:",
                    0, 3, null, options, options[0]);
            System.out.println("userAction:" + userAction);
            switch (userAction) {
                case 0 -> {
                    updateBtn.setEnabled(true);
                    saveBtn.setEnabled(false);
                    deleteBtn.setEnabled(false);
                    viewBtn.setEnabled(false);
                    userNameTxt.setEnabled(false);
                    firstNameTxt.setEnabled(false);
                    lastNameTxt.setEnabled(false);
                    chefRecipeTbl.clearSelection();
                    chefRecipeTbl.setEnabled(false);
                }
                case 1 -> {
                    deleteBtn.setEnabled(true);
                    saveBtn.setEnabled(false);
                    updateBtn.setEnabled(false);
                    viewBtn.setEnabled(false);
                    browseBtn.setEnabled(false);
                    userNameTxt.setEnabled(false);
                    firstNameTxt.setEnabled(false);
                    lastNameTxt.setEnabled(false);
                    emailTxt.setEnabled(false);
                    phoneTxt.setEnabled(false);
                    titleTxt.setEnabled(false);
                    servingsTxt.setEnabled(false);
                    glutenCombo.setEnabled(false);
                    difficultyCombo.setEnabled(false);
                    ingredientsTxt.setEnabled(false);
                    categoryCombo.setEnabled(false);
                    descTxtArea.setEnabled(false);
                    chefRecipeTbl.clearSelection();
                    chefRecipeTbl.setEnabled(false);
                }
                default ->
                    restFormFields();
            }
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (!validateForm()) {
            return;
        } else {
            if (saveForm()) {
                JOptionPane.showMessageDialog(null, "Record Saved Successfully");
                clearFormFields();
                new FBUtil().populateTable(chefRecipeTbl);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to save record");
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private boolean saveForm() {
        FBUtil fbUtil = setUserCategoryRecipe();
        boolean recordSaved = fbUtil.saveAll();
        return recordSaved;
    }

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        restFormFields();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (!validateForm()) {
            return;
        } else {
            if (updateForm()) {
                JOptionPane.showMessageDialog(null, "Record updated Successfully");
                restFormFields();
                new FBUtil().populateTable(chefRecipeTbl);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update record");
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private boolean updateForm() {
        FBUtil fbUtil = setUserCategoryRecipe();
        return fbUtil.update();
    }

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (!validateForm()) {
            return;
        } else {
            if (deleteForm()) {
                JOptionPane.showMessageDialog(null, "Record deleted Successfully");
                restFormFields();
                new FBUtil().populateTable(chefRecipeTbl);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete record");
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private boolean deleteForm() {
        FBUtil fbUtil = setUserCategoryRecipe();
        return fbUtil.delete();
    }

    private boolean validateForm() {
        if (Validations.isEmpty(userNameTxt, Constants.USERNAME_NO_BLANK) //|| Validations.userExist(userNameTxt, Constants.USERNAME_EXIST)
                ) {
            return false;
        }
        if (Validations.isEmpty(firstNameTxt, Constants.FIRSTNAME_NO_BLANK)) {
            return false;
        }
        if (Validations.isEmpty(lastNameTxt, Constants.LASTNAME_NO_BLANK)) {
            return false;
        }
        if (Validations.isEmpty(emailTxt, Constants.EMAIL_NO_BLANK)) {
            return false;
        }
        if (Validations.isEmailValid(emailTxt, Constants.EMAIL_INVALID)) {
            return false;
        }
        if (Validations.isEmpty(phoneTxt, Constants.PHONE_NO_BLANK)
                || Validations.checkMinLength(phoneTxt,
                        Constants.PHONE_NO_MIN_LENGTH,
                        Constants.PHONE_NO_LENGTH_INVALID)) {
            return false;
        }
//        if (Validations.phonenoExist(phoneTxt, Constants.PHONENO_EXIST)) {
//            return false;
//        }
        if (Validations.isEmpty(titleTxt, Constants.TITLE_NO_BLANK)) {
            return false;
        }
        if (Validations.isEmpty(servingsTxt, Constants.SERVINGS_NO_BLANK)) {
            return false;
        }
        if (Validations.isEmpty(ingredientsTxt, Constants.INGREDIENTS_NO_BLANK)) {
            return false;
        }
        if (Validations.isEmpty(descTxtArea, Constants.DESCRIPTION_NO_BLANK)) {
            return false;
        }
        if (Validations.isEmpty(imgFileName, recipePhotoDisplayLbl, Constants.IMAGE_NO_BLANK)) {
            return false;
        }
        return true;
    }

    private FBUtil setUserCategoryRecipe() {
        FBUtil fbUtil = new FBUtil();
        fbUtil.setUser(chefId, userNameTxt, firstNameTxt, lastNameTxt, emailTxt, phoneTxt);
        fbUtil.setCategory(categoryCombo);
        fbUtil.setRecipe(recipeId, titleTxt, servingsTxt, glutenCombo, difficultyCombo, ingredientsTxt, descTxtArea, imgFileName);
        return fbUtil;
    }

    private void clearFormFields() {
        userNameTxt.setText("");
        firstNameTxt.setText("");
        lastNameTxt.setText("");
        emailTxt.setText("");
        phoneTxt.setText("");

        titleTxt.setText("");
        servingsTxt.setText("");
        glutenCombo.setSelectedIndex(0);
        difficultyCombo.setSelectedIndex(0);
        ingredientsTxt.setText("");
        descTxtArea.setText("");
        categoryCombo.setSelectedIndex(0);
        recipePhotoDisplayLbl.setIcon(null);
        imgLabel.setText("");

        imgFileName = null;
        chefId = 0;
        recipeId = 0;
    }

    private void restFormFields() {
        saveBtn.setEnabled(true);
        deleteBtn.setEnabled(false);
        viewBtn.setEnabled(true);
        browseBtn.setEnabled(true);
        updateBtn.setEnabled(false);
        userNameTxt.setEnabled(true);
        userNameTxt.setBackground(Color.white);
        firstNameTxt.setEnabled(true);
        firstNameTxt.setBackground(Color.white);
        lastNameTxt.setEnabled(true);
        lastNameTxt.setBackground(Color.white);
        emailTxt.setEnabled(true);
        emailTxt.setBackground(Color.white);
        phoneTxt.setEnabled(true);
        phoneTxt.setBackground(Color.white);
        titleTxt.setEnabled(true);
        titleTxt.setBackground(Color.white);
        servingsTxt.setEnabled(true);
        servingsTxt.setBackground(Color.white);
        glutenCombo.setEnabled(true);
        glutenCombo.setBackground(Color.white);
        difficultyCombo.setEnabled(true);
        difficultyCombo.setBackground(Color.white);
        ingredientsTxt.setEnabled(true);
        ingredientsTxt.setBackground(Color.white);
        categoryCombo.setEnabled(true);
        categoryCombo.setBackground(Color.white);
        descTxtArea.setEnabled(true);
        descTxtArea.setBackground(Color.white);
        chefRecipeTbl.setEnabled(true);
        clearFormFields();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodBlogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodBlogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodBlogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodBlogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FoodBlogger mainFrame = new FoodBlogger();
                //new FBMainFrame().setVisible(true);
                mainFrame.setDefaultCloseOperation(FoodBlogger.EXIT_ON_CLOSE);

                // set the jframe size and location, and make it visible
                mainFrame.setPreferredSize(new Dimension(1210, 595));
                mainFrame.pack();
                mainFrame.setLocationRelativeTo(null);

                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JTable chefRecipeTbl;
    private javax.swing.JPanel chefUserPanel;
    private javax.swing.JPanel chefUserPanel1;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextArea descTxtArea;
    private javax.swing.JComboBox<String> difficultyCombo;
    private javax.swing.JLabel difficultyLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JComboBox<String> glutenCombo;
    private javax.swing.JLabel glutenLbl;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel ingredientsLbl;
    private javax.swing.JTextField ingredientsTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JLabel recipeLbl;
    private javax.swing.JPanel recipePanel;
    private javax.swing.JLabel recipePhotoDisplayLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel servingsLbl;
    private javax.swing.JTextField servingsTxt;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
